# app/services/report_generator.py
# PDF generation for the clinical brief.
# Uses pymupdf (already a dependency) — no new libraries needed.

import io
import pymupdf

from app.models.schemas import ClinicalBrief

_RISK_COLORS = {
    "low":       (0.18, 0.54, 0.34),
    "moderate":  (0.85, 0.55, 0.10),
    "high":      (0.80, 0.20, 0.20),
    "emergency": (0.55, 0.00, 0.00),
}

_AI_BG      = (0.92, 0.95, 1.00)   # light blue bubble
_PATIENT_BG = (0.95, 0.97, 0.93)   # light green bubble
_AI_LABEL   = (0.20, 0.35, 0.65)
_PAT_LABEL  = (0.20, 0.45, 0.20)
_FOOTER_Y   = 760


def to_pdf(brief: ClinicalBrief) -> bytes:
    """Render a ClinicalBrief as a PDF and return raw bytes."""
    doc  = pymupdf.open()
    W    = 572   # right margin

    def new_page():
        pg = doc.new_page(width=612, height=792)
        # Thin top rule on continuation pages
        pg.draw_line((40, 30), (W, 30), color=(0.80, 0.87, 0.95), width=0.5)
        pg.insert_text((40, 24), "PrelimMD — Clinical Brief (continued)", fontsize=7, color=(0.6, 0.6, 0.6))
        return pg, 48

    def add_footer(pg):
        pg.draw_line((40, _FOOTER_Y), (W, _FOOTER_Y), color=(0.80, 0.87, 0.95), width=0.5)
        pg.insert_text(
            (40, _FOOTER_Y + 14),
            f"Patient ID: {brief.patient_id}  |  Form ID: {brief.form_id}  |  Generated by PrelimMD",
            fontsize=7, color=(0.6, 0.6, 0.6),
        )

    # ── Helpers that are page-aware ────────────────────────────────────────────
    def section_header(pg, y, title, margin=30):
        """Draw a section rule + label; breaks to a new page if needed."""
        if y + margin > _FOOTER_Y - 20:
            add_footer(pg)
            pg, y = new_page()
        pg.draw_line((40, y), (W, y), color=(0.80, 0.87, 0.95), width=0.8)
        y += 6
        pg.insert_text((40, y + 10), title, fontsize=8, color=(0.5, 0.5, 0.5))
        return pg, y + 20

    def wrapped_text(pg, y, text, x=40, max_width=530, fontsize=10, color=(0.1, 0.1, 0.1)):
        words = text.split()
        line, lines = [], []
        for word in words:
            test = " ".join(line + [word])
            if pymupdf.get_text_length(test, fontname="helv", fontsize=fontsize) > max_width:
                lines.append(" ".join(line))
                line = [word]
            else:
                line.append(word)
        if line:
            lines.append(" ".join(line))
        for ln in lines:
            if y + fontsize + 4 > _FOOTER_Y - 20:
                add_footer(pg)
                pg, y = new_page()
            pg.insert_text((x, y), ln, fontsize=fontsize, color=color)
            y += fontsize + 4
        return pg, y

    def field_grid(pg, y, fields):
        col2_x, col, row_start_y = 316, 0, y
        for field in fields:
            if row_start_y + 30 > _FOOTER_Y - 20:
                add_footer(pg)
                pg, row_start_y = new_page()
                col = 0
                y = row_start_y
            cx = 40 if col == 0 else col2_x
            cy = y if col == 0 else row_start_y
            pg.insert_text((cx, cy),      field["label"],            fontsize=7, color=(0.55, 0.55, 0.55))
            pg.insert_text((cx, cy + 11), str(field["value"])[:55], fontsize=9, color=(0.1,  0.1,  0.1))
            if col == 0:
                col = 1
            else:
                col = 0
                row_start_y += 26
                y = row_start_y
        if col == 1:
            y = row_start_y + 26
        return pg, y + 4

    # ── Page 1 header ─────────────────────────────────────────────────────────
    page = doc.new_page(width=612, height=792)
    page.draw_rect(pymupdf.Rect(0, 0, 612, 70), color=None, fill=(0.10, 0.22, 0.38))
    page.insert_text((40, 28), "PrelimMD", fontsize=18, color=(1, 1, 1))
    page.insert_text((40, 48), "AI Pre-Screening — Clinical Brief", fontsize=10, color=(0.75, 0.85, 1.0))
    page.insert_text((400, 38), brief.created_at[:10], fontsize=9, color=(0.75, 0.85, 1.0))
    y = 90

    # ── Risk badge ────────────────────────────────────────────────────────────
    risk_color = _RISK_COLORS.get(brief.risk_level, (0.5, 0.5, 0.5))
    page.draw_rect(pymupdf.Rect(40, y, 140, y + 22), color=None, fill=risk_color)
    page.insert_text((48, y + 15), brief.risk_level.upper(), fontsize=10, color=(1, 1, 1))
    page.insert_text((150, y + 15), f"→  {brief.recommended_routing}", fontsize=11, color=(0.10, 0.22, 0.38))
    y += 36

    # ── Chief complaint ───────────────────────────────────────────────────────
    page.insert_text((40, y), "CHIEF COMPLAINT", fontsize=8, color=(0.5, 0.5, 0.5))
    y += 14
    page.insert_text((40, y), brief.chief_complaint, fontsize=13, color=(0.05, 0.15, 0.30))
    y += 22

    # ── Summary ───────────────────────────────────────────────────────────────
    page, y = section_header(page, y, "SUMMARY")
    page, y = wrapped_text(page, y, brief.summary)
    y += 8

    # ── Clinical notes ────────────────────────────────────────────────────────
    page, y = section_header(page, y, "CLINICAL NOTES")
    page, y = wrapped_text(page, y, brief.notes)
    y += 8

    # ── All form fields split by source ───────────────────────────────────────
    ehr_fields  = [f for f in brief.extracted_fields if f.get("source") == "ehr"]
    call_fields = [f for f in brief.extracted_fields if f.get("source") != "ehr"]

    if ehr_fields:
        page, y = section_header(page, y, "EHR FIELDS")
        page, y = field_grid(page, y, ehr_fields)

    if call_fields:
        page, y = section_header(page, y, "COLLECTED DURING CALL")
        page, y = field_grid(page, y, call_fields)

    # ── Nurse flags ───────────────────────────────────────────────────────────
    if brief.missing_information:
        page, y = section_header(page, y, "NURSE REVIEW")
        for item in brief.missing_information:
            page, y = wrapped_text(page, y, f"⚑  {item}", color=(0.75, 0.20, 0.20))
        y += 4

    # ── Transcript ────────────────────────────────────────────────────────────
    if brief.transcript:
        page, y = section_header(page, y, "CALL TRANSCRIPT", margin=50)
        y += 2
        for turn in brief.transcript:
            is_ai  = turn.role == "ai"
            label  = "Assistant" if is_ai else "Patient"
            lcolor = _AI_LABEL if is_ai else _PAT_LABEL
            bg     = _AI_BG    if is_ai else _PATIENT_BG
            x_off  = 40 if is_ai else 80
            bw     = 490 if is_ai else 450

            # Measure how many lines the bubble needs
            words = turn.content.split()
            line, lines = [], []
            for word in words:
                test = " ".join(line + [word])
                if pymupdf.get_text_length(test, fontname="helv", fontsize=9) > bw - 16:
                    lines.append(" ".join(line))
                    line = [word]
                else:
                    line.append(word)
            if line:
                lines.append(" ".join(line))

            bubble_h = 14 + len(lines) * 13 + 6
            if y + bubble_h + 6 > _FOOTER_Y - 20:
                add_footer(page)
                page, y = new_page()

            page.draw_rect(pymupdf.Rect(x_off, y, x_off + bw, y + bubble_h), color=None, fill=bg)
            page.insert_text((x_off + 8, y + 11), label, fontsize=7, color=lcolor)
            ty = y + 22
            for ln in lines:
                page.insert_text((x_off + 8, ty), ln, fontsize=9, color=(0.1, 0.1, 0.1))
                ty += 13
            y += bubble_h + 5

    # ── Footer on last page ────────────────────────────────────────────────────
    add_footer(page)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
